title: Ágatha de Freitas  # You can add your name here

logo: Me.jpeg # Use a relative path to logo image 

description: M.Sc. in Information Security at Universidade de São Paulo # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: agathadefreitas@proton.me # Allow visitors to contact you
